### PR TITLE
chore: Update metrics to 0.22.1

### PR DESCRIPTION
**Pull request by fitzthum**
Pick up fixes for ahash

### CODE REVIEW

**Comment by fitzthum** [comment]
Looks like there are some fixes required. I'll take a look.

**Comment by garrensmith** [comment]
Thanks this looks good. Do you think this will be a breaking change for downstream users of mobc? If they using an older version of metrics this will break their usage.

**Comment by fitzthum** [comment]
I don't think so, but I am not very familiar with either of these crates. Seems like these changes only apply to emission of metrics and not crates that consume them. 

You might glance at [this section](https://github.com/metrics-rs/metrics/blob/main/metrics/RELEASES.md#macros-overhaul) of the metrics release notes to see if you have the same impression.

**Comment by garrensmith** [comment]
Awesome thanks

**Pull request merged**
